drop table if exists users cascade;
drop table if exists user_friends cascade;
drop table if exists rating cascade;
drop table if exists films cascade;
drop table if exists film_likes cascade;
drop table if exists genre cascade;
drop table if exists film_genre cascade;

create table if not exists users (
user_id int not null generated by default as identity primary key,
name varchar not null,
email varchar(320) not null,
login varchar(255) not null,
birthday date
);

create table if not exists user_friends (
user_id int not null references users(user_id),
friend_id int not null references users(user_id)
);

create table if not exists rating (
rating_id int not null generated by default as identity primary key,
name varchar(5) not null
);

create table if not exists films (
film_id int not null generated by default as identity primary key,
name varchar not null,
description varchar(200) not null,
release_date date not null,
duration int not null,
rating_id int not null references rating(rating_id)
);

create table if not exists film_likes (
film_id int not null references films(film_id),
 user_id int not null references users(user_id)
);

create table if not exists genre (
genre_id int not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) not null
);

create table if not exists film_genre (
genre_id int not null references genre(genre_id),
film_id  int not null references films(film_id)
);


