drop table IF EXISTS users CASCADE;
drop table IF EXISTS user_friends CASCADE;
drop table IF EXISTS rating CASCADE;
drop table IF EXISTS FILM CASCADE;
drop table IF EXISTS films CASCADE;
drop table IF EXISTS film_likes CASCADE;
drop table IF EXISTS genre CASCADE;
drop table IF EXISTS film_genre CASCADE;

create table if not exists users (
    user_id  int not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar not null,
    email    varchar(320) not null,
    login    varchar(255) not null,
    birthday date
  );

create table if not exists user_friends (
user_id   int not null references users(user_id),
friend_id int not null references users(user_id)

);

create TABLE if not exists rating (
    rating_id int not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(5) not null
);

create table if not exists films
(
  film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar not null,
  description varchar(200) not null,
  release_date date not null,
  duration int not null,
  rating_id int not null references rating(rating_id)
  CONSTRAINT check_release_date CHECK (release_date > '1895-12-28'),
  CONSTRAINT check_duration CHECK (duration > 0)
);

create table if not exists film_likes  (
    film_id int not null references films(film_id),
    user_id int not null references users(user_id)
);

create TABLE if not exists genre (
      genre_id int not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name varchar(255) not null
  );

create TABLE if not exists film_genre (
    genre_id int not null references genre(genre_id),
    film_id  int not null references films(film_id)
);


